spring:
  application:
    name: TmsS
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/TmsS?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform : org.hibernate.dialect.MySQL8Dialect
    show-sql: true



