server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

spring:
  application:
    name: discovery-services
  config:
    import: optional:configserver:http://localhost:8888
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 60000
  cache:
    type: redis
  cloud:
    inetutils:
      preferred-networks:
        - 192.168
      ignored-interfaces:
        - docker0
        - veth

logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: DEBUG